// <auto-generated />
namespace SystemaVidanta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SystemaVidantaModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SystemaVidantaModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202104212139006_SystemaVidanta.Models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
